Repository spicetify/spicetify-themes, pull requests merged in 2022-04, with the labels that each got.

#710 fix(BurntSienna): Some visual fixes
  BurntSienna/user.css
Labels: 🙋 help wanted

#696 fix(Turntable): repair invalid styles
  Turntable/user.css
Labels: 🙋 help wanted

#723 Glaze theme patches
  Glaze/manifest.json
  Glaze/user.css
Labels: 🐛 bug

#715 feat(Bloom): create new theme
  Bloom/Dark-1.png
  Bloom/LICENSE
  Bloom/README.md
  Bloom/assets/fluentui-system-icons/LICENSE
  Bloom/assets/fluentui-system-icons/ic_fluent_add_circle_24_regular.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_arrow_left_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_arrow_repeat_all_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_arrow_repeat_all_off_24_regular.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_arrow_repeat_all_once_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_arrow_right_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_arrow_up_right_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_arrow_up_right_24_regular.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_folder_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_heart_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_home_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_home_24_regular.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_library_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_library_24_regular.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_mic_on_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_music_note_2_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_next_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_pause_16_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_play_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_previous_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_search_12_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_search_16_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_search_16_regular.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_search_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_search_24_regular.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_skip_backward_15_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_skip_forward_15_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_slide_text_24_filled.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_slide_text_24_regular.svg
  Bloom/assets/fluentui-system-icons/ic_fluent_top_speed_24_filled.svg
  Bloom/assets/phosphor-icons/LICENSE
  Bloom/assets/phosphor-icons/shuffle-bold.svg
  Bloom/assets/phosphor-icons/shuffle-light.svg
  Bloom/assets/phosphor-icons/shuffle.svg
  Bloom/bloom.js
  Bloom/color.ini
  Bloom/install.ps1
  Bloom/install.sh
  Bloom/user.css
Labels: ➕ theme addition
