Repository spicetify/spicetify-themes, pull requests merged in 2022-03, with the labels that each got.

#701 remove: fluent
  Fluent/LICENSE
  Fluent/README.md
  Fluent/assets/fluentui-system-icons/LICENSE
  Fluent/assets/fluentui-system-icons/ic_fluent_add_circle_24_regular.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_arrow_left_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_arrow_repeat_all_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_arrow_repeat_all_off_24_regular.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_arrow_repeat_all_once_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_arrow_right_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_arrow_up_right_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_arrow_up_right_24_regular.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_folder_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_heart_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_home_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_home_24_regular.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_library_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_library_24_regular.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_mic_on_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_music_note_2_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_next_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_pause_16_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_play_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_previous_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_search_12_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_search_16_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_search_16_regular.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_search_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_search_24_regular.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_skip_backward_15_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_skip_forward_15_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_slide_text_24_filled.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_slide_text_24_regular.svg
  Fluent/assets/fluentui-system-icons/ic_fluent_top_speed_24_filled.svg
  Fluent/assets/phosphor-icons/LICENSE
  Fluent/assets/phosphor-icons/shuffle-bold.svg
  Fluent/assets/phosphor-icons/shuffle-light.svg
  Fluent/assets/phosphor-icons/shuffle.svg
  Fluent/color.ini
  Fluent/fluent.js
  Fluent/screenshots/comfy-1.jpg
  Fluent/screenshots/comfy-2.jpg
  Fluent/screenshots/dark-1.png
  Fluent/screenshots/dark-2.png
  Fluent/screenshots/light-1.png
  Fluent/user.css
  README.md
  THEMES.md
Labels: ☠️ unmantained

#700 feat: add auto-assign to themes issues and PRs
  .github/workflows/auto-assign.yml
Labels: ✨ enhancement, 🙋 help wanted

#707 Sleek: update all aspects
  Sleek/bladerunner.png
  Sleek/cherry.png
  Sleek/color.ini
  Sleek/coral.png
  Sleek/deep.png
  Sleek/deeper.png
  Sleek/dracula.png
  Sleek/elementary.png
  Sleek/futura.png
  Sleek/nord.png
  Sleek/psycho.png
  Sleek/ultrablack.png
  Sleek/user.css
  Sleek/wealthy.png
Labels: 🐛 bug
